### ISSUE TITLE
Crash when clicking My Apps.

### ISSUE THREAD

**Issue by sharpninja** [yoshiask/FluentStore#52]
### Before you start...

- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11, Windows 11 Dev

### What OS/App version/architecture are you seeing the problem on?

Edition	Windows 11 Pro
Version	22H2
Installed on	‎5/‎12/‎2022
OS build	22622.440
Serial number	PF38AS0N
Experience	Windows Feature Experience Pack 1000.22634.1000.0

### Description

![image](https://user-images.githubusercontent.com/16146732/182003065-ab167692-5e8a-4e76-a431-6e053354c89b.png)

Clicking My Apps crashes both the current distributed version and also running in the debugger.

The correct commit to replicate this result is: https://github.com/sharpninja/FluentStore/tree/737ab0aab6a075e6dff3ff59f25835bb09a4cc67

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll
An exception of type 'System.Runtime.InteropServices.COMException' occurred in WinRT.Runtime.dll but was not handled in user code
Element not found. (0x80070490)

'FluentStore.App.exe' (Win32): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. 
'FluentStore.App.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FluentStore.App.exe' (Win32): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.Impl.dll'. 
'FluentStore.App.exe' (Win32): Loaded 'C:\GitHub\FluentStore\FluentStore.App\bin\x64\Debug\net6.0-windows10.0.22000.0\AppX\CommunityToolkit.WinUI.Notifications.dll'. 
'FluentStore.App.exe' (CoreCLR: clrhost): Loaded 'C:\GitHub\FluentStore\FluentStore.App\bin\x64\Debug\net6.0-windows10.0.22000.0\AppX\CommunityToolkit.WinUI.Notifications.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
=== FATAL EXCEPTION ===
App.xaml.cs_L199_OnUnhandledException() : System error.
System.Threading.ThreadAbortException: System error.
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)
   at Windows.Win32.PInvoke.DefSubclassProc(HWND hWnd, UInt32 uMsg, WPARAM wParam, LPARAM lParam)
   at WinUIEx.Messaging.WindowMessageMonitor.NewWindowProc(HWND hWnd, UInt32 uMsg, WPARAM wParam, LPARAM lParam, UIntPtr uIdSubclass, UIntPtr dwRefData)
=== =============== ===
onecore\com\combase\dcomrem\giptbl.cxx(1796)\combase.dll!00007FFD35725BAC: (caller: 00007FFD35719B70) ReturnHr(507) tid(7644) 8000FFFF Catastrophic failure
onecore\com\combase\objact\dllhost.cxx(353)\combase.dll!00007FFD3580893D: (caller: 00007FFD35718450) ReturnHr(508) tid(7644) 8000FFFF Catastrophic failure
onecore\com\combase\objact\dllcache.cxx(1885)\combase.dll!00007FFD35808961: (caller: 00007FFD35718450) ReturnHr(509) tid(7644) 8000FFFF Catastrophic failure
onecore\com\combase\objact\dllcache.cxx(4023)\combase.dll!00007FFD35808A1A: (caller: 00007FFD35718450) ReturnHr(510) tid(7644) 8000FFFF Catastrophic failure
onecore\com\combase\winrt\error\restrictederror.cpp(1017)\combase.dll!00007FFD3574C4FA: (caller: 00007FFD35751A6F) ReturnHr(511) tid(7644) 8007007E The specified module could not be found.
'FluentStore.App.exe' (Win32): Loaded 'C:\Windows\System32\msxml6.dll'. 
'FluentStore.App.exe' (Win32): Loaded 'C:\Windows\System32\wpnapps.dll'. 
Exception thrown at 0x00007FFD33B7FB1C (KernelBase.dll) in FluentStore.App.exe: WinRT originate error - 0x80040111 : 'Windows.UI.Notifications.ToastNotification'.
The program '[20088] FluentStore.App.exe' has exited with code 0 (0x0).
```

### Steps To Reproduce

1. Clone: https://github.com/sharpninja/FluentStore/tree/737ab0aab6a075e6dff3ff59f25835bb09a4cc67
2. Open in VS2022 17.3.0 Preview 3.0
3. Set `FluentStore.App` as the startup project.
4. Start Debugger
5. After everything loads, click `My Apps`.
6. Crash.

### Expected behavior

Don't crash.

**Comment by yoshiask** [comment]
I checked out the commit you linked, but you've edited almost every C# file in every project, I can't tell what actually has changed. Are you able to repro this with the latest release?

**Comment by yoshiask** [comment]
If I don't hear back in a couple of days, I'm going to close this issue.

**Comment by sharpninja** [comment]
You can close it.  I don't have time to retrace my steps to answer your question.

The Sharp Ninja
GH: @sharpninja


------- Original Message -------

**Comment by mediaexplorer74** [comment]
> https://github.com/sharpninja/FluentStore/tree/737ab0aab6a075e6dff3ff59f25835bb09a4cc67

You deleted your "fork" : https://github.com/sharpninja/FluentStore/ not found. Too bad.
